---
- name: Ensure GNOME's initial setup screen is marked as complete
  ansible.builtin.copy:
    content: "yes"
    dest: "{{ ansible_env.HOME }}/.config/gnome-initial-setup-done"
- name: Ensure dconf settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
    state: present
  with_items: "{{ desktop_environment_gnome_dconf_settings }}"
