---
- hosts: all

  pre_tasks:
    - name: Load Playbook config
      include_tasks: config/config.yml

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        lock_timeout: "{{ apt_lock_timeout }}"
      changed_when: false
      become: true

- name: Include Setup play
  ansible.builtin.import_playbook: setup.yml
