---
- hosts: all

  pre_tasks:
    - name: Load Playbook config
      include_tasks: config/config.yml

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        lock_timeout: "{{ apt_lock_timeout }}"
      changed_when: false
      become: true

  roles:
    - role: bootstrap
    - role: update
    - role: base_system
    - role: packages
    - role: dev_tools
      vars:
        dev_tools_install_jetbrains_toolbox: "{{ install_jetbrains_toolbox }}"
        dev_tools_install_vscode: "{{ install_vscode }}"
        dev_tools_install_vscodium: "{{ install_vscodium }}"
        dev_tools_install_pyenv: "{{ install_pyenv }}"
        dev_tools_install_nvm: "{{ install_nvm }}"
        dev_tools_install_pipx: "{{ install_pipx }}"
        dev_tools_vscode_extensions: "{{ vscode_extensions }}"
        dev_tools_vscodium_extensions: "{{ vscodium_extensions }}"
    - role: guest_additions
      when: is_virtual_machine
    - role: desktop_environment
