---
collections:
  - name: community.general
    version: 7.4.0
roles:
  - name: diodonfrost.jetbrains_toolbox
    version: 0.9.0
  - name: gantsign.visual-studio-code-extensions
    version: 2.4.0
  - name: green_leader.codium
    version: 1.0.4
