---
collections:
  - name: community.general
    version: 5.4.0
roles:
  - name: diodonfrost.jetbrains_toolbox
    version: 0.9.0
  - name: ecgalaxy.vscode
    version: 1.3.1
  - name: green_leader.codium
    version: 1.0.4
