---
- hosts: all
  vars_files:
    - vars/vault.yml

  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false
      become: true

  tasks:
    - name: Make sure APT packages are updated
      ansible.builtin.apt:
        upgrade: safe
      become: true
