---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        lock_timeout: "{{ apt_lock_timeout }}"
      changed_when: false
      become: true

  tasks:
    - name: Make sure APT packages are updated
      ansible.builtin.apt:
        upgrade: safe
        lock_timeout: "{{ apt_lock_timeout }}"
      become: true
