---
- name: Install Pyenv
  import_role:
    name: pyenv
  when: dev_tools_install_pyenv
- name: Install Pipx
  ansible.builtin.apt:
    name: pipx
    state: present
    lock_timeout: "{{ apt_lock_timeout }}"
  become: true
  when: dev_tools_install_pipx
