---
- name: Ensure VS Code's repository is present
  import_role:
    name: extrepo
  vars:
    extrepo_allow_non_free_repositories: true
    extrepo_enabled_repositories:
      - vscode
- name: Install VS Code
  ansible.builtin.apt:
    name: code
    state: present
    lock_timeout: "{{ apt_lock_timeout }}"
  become: true
- name: Install extentions for VS Code
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions: "{{ dev_tools_vscode_extensions }}"
  become: true
