---
- name: Ensure VS Code's repository is present
  import_role:
    name: extrepo
  vars:
    extrepo_allow_non_free_repositories: true
    extrepo_enabled_repositories:
      - vscode

# TODO: Remove this when this is done: https://github.com/microsoft/vscode/issues/190960
- name: Workaround VS Code package's postinst script
  ansible.builtin.copy:
    content: |
      # This is simply a workaround for VS Code package's postinst script.
      # The postinst script would (over)write a file named:
      # `/etc/apt/sources.d/vscode.list` in a couple of circumstances.
      # We are targeting this rule specifically:
      # https://github.com/microsoft/vscode/blob/4b9608ccceba9fee3d5ceb5f76e0b728d7a05068/resources/linux/debian/postinst.template#L43
      #
      # People have already requested this functionality to be removed:
      # Issue: https://github.com/microsoft/vscode/issues/190960
    dest: "/etc/apt/sources.list.d/vscode.list"
  become: true

- name: Install VS Code
  ansible.builtin.apt:
    name: code
    state: present
    lock_timeout: "{{ apt_lock_timeout }}"
  become: true
- name: Install extentions for VS Code
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions: "{{ dev_tools_vscode_extensions }}"
  become: true
