---
_common_packages:
  - ntfs-3g
  - python3-pip
  - python3-venv
  # Cli
  - apt-file
  - bsdutils
  - etckeeper
  - fdisk
  - gddrescue
  - git
  - gnupg
  - htop
  - less
  - net-tools
  - rsync
  - smbclient
  - sudo
  - telnet
  - testdisk
  - tree
  - unrar
  - vim
  - xxd
  - powerline
  - alacritty
  # Gui
  - qdirstat
  - vlc
  - gparted
  - keepass2
  - timeshift

_packages: "{{ _common_packages + (_vm_packages_extra | default([])) + (_physical_packages_extra | default([]))}}"

_flatpaks:
  - com.slack.Slack
  - org.remmina.Remmina

install_jetbrains_toolbox: true
install_vscode: true
install_vscodium: true
install_pyenv: true
install_nvm: true
install_pipx: true
