---
_common_packages:
  - ntfs-3g
  - python3-pip
  - python3-venv
  - libfuse2
  # Cli
  - apt-file
  - bsdutils
  - etckeeper
  - fdisk
  - gddrescue
  - git
  - gnupg
  - htop
  - less
  - net-tools
  - rsync
  - smbclient
  - sudo
  - telnet
  - testdisk
  - tree
  - vim
  - xxd
  - powerline
  - alacritty
  # Gui
  - qdirstat
  - vlc
  - gparted
  - keepass2
  - timeshift
  - brave-browser

_packages: "{{ _common_packages + (_vm_packages_extra | default([])) + (_physical_packages_extra | default([]))}}"

_flatpaks:
  - com.slack.Slack
  - org.remmina.Remmina

install_jetbrains_toolbox: true
install_vscode: true
install_vscodium: true
install_pyenv: true
install_nvm: true
install_pipx: true
vscode_extensions:
  - eamodio.gitlens
  - ms-python.python
  - ms-azuretools.vscode-docker
  - editorconfig.editorconfig
  - wayou.vscode-todo-highlight
  - foxundermoon.shell-format
  - redhat.vscode-yaml
  - tamasfe.even-better-toml
  - hashicorp.terraform
vscodium_extensions: "{{ vscode_extensions }}"

default_extrepo_repositories:
  - 'brave_release'
