---
- name: Check if pyenv is installed
  ansible.builtin.stat:
    path: '{{ pyenv_root_path }}'
  register: pyenv_root_stat_result
- name: Install Pyenv
  block:
    - name: Download pyenv-installer script
      ansible.builtin.get_url:
        url: '{{ pyenv_installer_script_url }}'
        dest: '{{ pyenv_installer_script_path }}'
        checksum: '{{ pyenv_installer_script_checksum }}'
        mode: '0544'
    - name: Execute the pyenv-installer script
      ansible.builtin.command:
        cmd: '{{ pyenv_installer_script_path }}'
        creates: '{{ pyenv_root_path }}'
      environment:
        PYENV_ROOT: '{{ pyenv_root_path }}'

    - name: Remove the pyenv-installer script
      ansible.builtin.file:
        path: '{{ pyenv_installer_script_path }}'
        state: absent
  when: not pyenv_root_stat_result.stat.exists
