---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    lock_timeout: "{{ apt_lock_timeout }}"
  changed_when: false
  become: true

- name: Install Python build dependencies
  ansible.builtin.apt:
    name: "{{ pyenv_python_build_dependencies }}"
    state: present
  become: true
