---
pyenv_root_path: "{{ ansible_env.HOME }}/.local/share/pyenv"
pyenv_installer_commit_id: 'ceaff5492cb3ebe962c8b7ad1b408dab9a56e71b'
pyenv_installer_script_url: 'https://github.com/pyenv/pyenv-installer/raw/{{ pyenv_installer_commit_id }}/bin/pyenv-installer'
pyenv_installer_script_checksum: 'sha256:2459846fd01ab383fb9dcf6854116ab6b044039dc34ab2485085473a48d28b64'
pyenv_installer_script_path: /tmp/pyenv-installer

# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
pyenv_python_build_dependencies:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
