---
pyenv_root_path: "{{ ansible_env.HOME }}/.local/share/pyenv"
pyenv_installer_script_url: 'https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer'
pyenv_installer_script_checksum: 'sha256:33ba007f17d31215349fd0a693a77fd3d332063fb3a44b8994dfde87728b94e1'
pyenv_installer_script_path: /tmp/pyenv-installer

# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
pyenv_python_build_dependencies:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
